[tool.poetry]
name = "{{cookiecutter.project_name}}"
version = "0.1.0"
description = "{{cookiecutter.project_description}}"
authors = ["{{cookiecutter.author_name}} <{{cookiecutter.author_email}}>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/{{cookiecutter.author_github_name}}/{{cookiecutter.project_name}}"
repository = "https://github.com/{{cookiecutter.author_github_name}}/{{cookiecutter.project_name}}.git"


[tool.poetry.dependencies]
python = "3.10"


[tool.poetry.dev-dependencies]
pytest = "6.2.5"
black = { version = "*", allow-prereleases = true }
isort = "^5.10.1"
pylint = "2.12.1"


[tool.pytest.ini_options]
testpaths = [
    "tests",
]


[tool.black]
line-length = 88
target-version = ['py310']
include = '\.pyi?$'


[tool.isort]
profile = "black"


[tool.pylint.messages_control]
max-line-length = 88
disable = "C0330, C0326"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
